# !vars
offsets:
  - &_EXAMPLE 0

# !main
system:
  PORTNAME: '/dev/ttyUSB0'
  BAUDRATE: 1000000
  PROTOCOL_VERSION: 2.0
  ROBOT_NAME: "Dynamixel ARM"
  RECALIBRATE: False

  ANGLE_STANDARD: DEGREE

actuator:
  XM430:
    counter_per_range: 4096
    range_deg: 360.0

gripper:
  finger_right:
    id: 1
    series: XM430
    torque_limit: 0.1
    velocity_limit: 0.05
    positive_direction: "CCW"
    calibration_enc: 0
  finger_left:
    id: 2
    series: XM430
    torque_limit: 0.1
    velocity_limit: 0.05
    positive_direction: "CCW"
    calibration_enc: 0